### ISSUE TITLE
No results found when looking for title

### ISSUE THREAD

**Issue by miclargeone** [MefhigosetH/vikeep#15]
hello it has been 2 weeks since the last time i was able to successfully access : http://vikeep.herokuapp.com/index.php.. whenever i am searching for a drama like: "it's okay it's love" it's not working.. even if i am searching ~ Running Man.

will appreciate your help. :)

**Comment by MefhigosetH** [comment]
Fixed in latest commit. Thanks for your feedback.

**Comment by tabarak105** [comment]
Hi 
For example " The King's Face - 왕의 얼굴 " 
**viki link :**  viki.com/tv/24782c-the-kings-face
But in searching by various Of related word ( King ; face ; kings-face & ... ) I cant find this series
when I  manually Create a link , nothing happend Too
( vikeep.herokuapp.com/index.php?serie=24782c )
Then I must Add episode code from viki.com manually ( viki.com/videos/**1055697v**-the-kings-face-episode-1) To Your Address To can downloads that episode : (vikeep.herokuapp.com/index.php?episode=**1055697v**)
I know a few viki series only Shows in some Country .( is this related to limited zone ? )
