### ISSUE TITLE
Search Result Limited By 5 (in new change)

### ISSUE THREAD

**Issue by tabarak105** [MefhigosetH/vikeep#19]
Hi
In past when we search "King" Or "a", result showed at least **+10** series title but now result show only **5** series, 
Can you remove this limitation
Thanks for your great work

**Comment by MefhigosetH** [comment]
Hi @tabarak105 , thanks for your comment.

This issue allready has been documented on the latest comment at www.mefhigoseth.com.ar/2013/04/vikicom-video-downloader.html

I have found a solution for this, and fix it in a few days.

**Comment by tabarak105** [comment]
Thank you for taking the time & your support

**Comment by MefhigosetH** [comment]
Fixed.

**Comment by tabarak105** [comment]
Very Very Thanks
